"""Add title column to devotion_sessions

Revision ID: a800969b8ae9
Revises: 8cc903378bdb
Create Date: 2025-06-03 10:40:17.446066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a800969b8ae9'
down_revision: Union[str, None] = '8cc903378bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devotion_sessions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devotion_sessions', 'title')
    # ### end Alembic commands ###
